# Generated by Django 5.0.14 on 2026-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('push', 'Empuje'), ('pull', 'Jalón'), ('legs', 'Pierna'), ('core', 'Core'), ('cardio', 'Cardio')], max_length=20)),
                ('type', models.CharField(choices=[('strength', 'Pesas'), ('cardio', 'Cardio'), ('mobility', 'Movilidad'), ('bodyweight', 'Peso corporal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
